export default {
  subtitle: "Essential insights for foreign investors to understand and fulfil Permanent Establishment requirements in Uzbekistan.",
  author: "Advizen Tax Practice",
  readTime: "7 min read",
  content: [
    {
      type: "p" as const,
      text: "For foreign companies looking to operate in Uzbekistan, understanding the concept of a Permanent Establishment (PE) is fundamental. Essentially, a PE is established when a foreign company has a fixed place through which it conducts business activities within Uzbekistan. This can be a physical location or certain types of ongoing activities within the country. If a workplace is established for more than one month, it generally counts as a permanent workplace.",
    },
    { type: "h2" as const, text: "What Might Be Considered a PE?" },
    {
      type: "p" as const,
      text: "Various activities and presences can lead to PE status:",
    },
    {
      type: "ul" as const,
      items: [
        "Physical Locations: any type of office (management, branch, bureau), a factory, workshop, or laboratory",
        "Production & Sales: manufacturing, processing, or packaging goods, or using a warehouse as a sales point",
        "Resource Extraction: activities related to mining, oil or gas wells, quarries, or any other natural resource extraction",
        "Long-Term Projects & Services: construction, assembly, or installation projects lasting over 183 days; or providing services through employees for at least 183 days",
        "Insurance & Agency: foreign insurance companies collecting premiums through a dependent agent, or anyone consistently concluding contracts on behalf of the foreign company",
      ],
    },
    { type: "h2" as const, text: "When is a PE Not Created?" },
    {
      type: "p" as const,
      text: "Certain activities are generally considered preparatory or auxiliary and do not automatically lead to a PE:",
    },
    {
      type: "ul" as const,
      items: [
        "Storage and Display: using facilities solely for storing or displaying goods",
        "Limited Activities: maintaining a fixed place of business purely for purchasing goods or collecting information for preparatory purposes",
        "Personnel Provision (with conditions): providing foreign personnel to another company in Uzbekistan usually will not create a PE if your company is not responsible for their work results and your income from this does not exceed 10% of total costs for providing that personnel",
      ],
    },
    { type: "h2" as const, text: "Starting Operations and Registration" },
    {
      type: "p" as const,
      text: "If your activities indicate a PE, you are generally considered to have started operating in Uzbekistan on the earliest of several key dates — such as the signing of relevant contracts or the arrival of personnel for contract fulfilment. Once a PE is established, your foreign company is required to register with the local tax authorities.",
    },
    { type: "h2" as const, text: "Taxation and Deductible Expenses" },
    {
      type: "ul" as const,
      items: [
        "Income generated by your PE in Uzbekistan is subject to local corporate income tax",
        "The tax base is generally your PE's total income, considering specific deductions for business-related expenses",
        "Certain payments from the PE to your foreign head office or other related entities may not be deductible",
        "Net profit of the PE, after tax, is treated as dividends and may be subject to a 10% tax — though international tax treaties may offer lower rates",
      ],
    },
    {
      type: "blockquote" as const,
      text: "The PE rules in Uzbekistan closely follow OECD principles but with local specificities. Foreign companies should obtain a professional assessment before commencing operations to avoid unexpected tax exposure.",
    },
    { type: "h2" as const, text: "Practical Implications" },
    {
      type: "p" as const,
      text: "Understanding whether your activities create a PE in Uzbekistan is a critical step in any market entry analysis. The consequences of unregistered PE activity include back-taxes, penalties, and reputational risk. A proactive assessment of your operational footprint against the PE thresholds set out in Uzbekistan's Tax Code and relevant double tax treaties is strongly recommended before committing to a business structure.",
    },
  ],
};
