import type { LocalizedArticle } from "../publications";

const article: Record<string, LocalizedArticle> = {
  en: {
    subtitle: "Essential insights for foreign investors to understand and fulfil Permanent Establishment requirements in Uzbekistan.",
    author: "Advizen Tax Practice",
    readTime: "7 min read",
    content: [
      {
        type: "p",
        text: "For foreign companies looking to operate in Uzbekistan, understanding the concept of a Permanent Establishment (PE) is fundamental. Essentially, a PE is established when a foreign company has a fixed place through which it conducts business activities within Uzbekistan. This can be a physical location or certain types of ongoing activities within the country. If a workplace is established for more than one month, it generally counts as a permanent workplace.",
      },
      { type: "h2", text: "What Might Be Considered a PE?" },
      {
        type: "p",
        text: "Various activities and presences can lead to PE status:",
      },
      {
        type: "ul",
        items: [
          "Physical Locations: any type of office (management, branch, bureau), a factory, workshop, or laboratory",
          "Production & Sales: manufacturing, processing, or packaging goods, or using a warehouse as a sales point",
          "Resource Extraction: activities related to mining, oil or gas wells, quarries, or any other natural resource extraction",
          "Long-Term Projects & Services: construction, assembly, or installation projects lasting over 183 days; or providing services through employees for at least 183 days",
          "Insurance & Agency: foreign insurance companies collecting premiums through a dependent agent, or anyone consistently concluding contracts on behalf of the foreign company",
        ],
      },
      { type: "h2", text: "When is a PE Not Created?" },
      {
        type: "p",
        text: "Certain activities are generally considered preparatory or auxiliary and do not automatically lead to a PE:",
      },
      {
        type: "ul",
        items: [
          "Storage and Display: using facilities solely for storing or displaying goods",
          "Limited Activities: maintaining a fixed place of business purely for purchasing goods or collecting information for preparatory purposes",
          "Personnel Provision (with conditions): providing foreign personnel to another company in Uzbekistan usually will not create a PE if your company is not responsible for their work results and your income from this does not exceed 10% of total costs for providing that personnel",
        ],
      },
      { type: "h2", text: "Starting Operations and Registration" },
      {
        type: "p",
        text: "If your activities indicate a PE, you are generally considered to have started operating in Uzbekistan on the earliest of several key dates — such as the signing of relevant contracts or the arrival of personnel for contract fulfilment. Once a PE is established, your foreign company is required to register with the local tax authorities.",
      },
      { type: "h2", text: "Taxation and Deductible Expenses" },
      {
        type: "ul",
        items: [
          "Income generated by your PE in Uzbekistan is subject to local corporate income tax",
          "The tax base is generally your PE's total income, considering specific deductions for business-related expenses",
          "Certain payments from the PE to your foreign head office or other related entities may not be deductible",
          "Net profit of the PE, after tax, is treated as dividends and may be subject to a 10% tax — though international tax treaties may offer lower rates",
        ],
      },
      {
        type: "blockquote",
        text: "The PE rules in Uzbekistan closely follow OECD principles but with local specificities. Foreign companies should obtain a professional assessment before commencing operations to avoid unexpected tax exposure.",
      },
      { type: "h2", text: "Practical Implications" },
      {
        type: "p",
        text: "Understanding whether your activities create a PE in Uzbekistan is a critical step in any market entry analysis. The consequences of unregistered PE activity include back-taxes, penalties, and reputational risk. A proactive assessment of your operational footprint against the PE thresholds set out in Uzbekistan's Tax Code and relevant double tax treaties is strongly recommended before committing to a business structure.",
      },
    ],
  },
  ru: {
    subtitle: "Ключевые ориентиры для иностранных инвесторов в понимании и выполнении требований к Постоянному учреждению в Узбекистане.",
    author: "Налоговая практика Advizen",
    readTime: "7 мин чтения",
    content: [
      {
        type: "p",
        text: "Для иностранных компаний, планирующих деятельность в Узбекистане, понимание концепции постоянного учреждения (ПУ) принципиально. По сути, ПУ возникает, когда у иностранной компании есть постоянное место, через которое она ведёт предпринимательскую деятельность в Узбекистане. Это может быть физическая локация или определённые виды длящейся деятельности в стране. Рабочее место, существующее более одного месяца, как правило, считается постоянным.",
      },
      { type: "h2", text: "Что может считаться ПУ?" },
      {
        type: "p",
        text: "К статусу ПУ могут привести различные виды деятельности и присутствия:",
      },
      {
        type: "ul",
        items: [
          "Физические локации: любой тип офиса (управление, филиал, бюро), завод, мастерская или лаборатория",
          "Производство и продажи: производство, переработка или упаковка товаров, либо использование склада как точки продаж",
          "Добыча ресурсов: деятельность, связанная с добычей полезных ископаемых, нефтяных или газовых скважин, карьеров или иных природных ресурсов",
          "Длительные проекты и услуги: строительные, монтажные или установочные проекты длительностью более 183 дней; либо оказание услуг через работников на протяжении не менее 183 дней",
          "Страхование и агентирование: иностранные страховые компании, собирающие премии через зависимого агента, или лица, систематически заключающие договоры от имени иностранной компании",
        ],
      },
      { type: "h2", text: "Когда ПУ не возникает?" },
      {
        type: "p",
        text: "Определённые виды деятельности обычно рассматриваются как подготовительные или вспомогательные и сами по себе не создают ПУ:",
      },
      {
        type: "ul",
        items: [
          "Хранение и демонстрация: использование помещений исключительно для хранения или демонстрации товаров",
          "Ограниченная деятельность: содержание постоянного места деятельности исключительно для закупки товаров или сбора информации в подготовительных целях",
          "Предоставление персонала (с условиями): предоставление иностранного персонала другой компании в Узбекистане обычно не создаёт ПУ, если ваша компания не отвечает за результаты их работы, а ваш доход от этого не превышает 10% общих расходов на предоставление такого персонала",
        ],
      },
      { type: "h2", text: "Начало деятельности и регистрация" },
      {
        type: "p",
        text: "Если ваша деятельность указывает на ПУ, обычно считается, что вы начали деятельность в Узбекистане с наиболее ранней из ряда ключевых дат — например, подписания соответствующих договоров или прибытия персонала для выполнения контракта. После возникновения ПУ ваша иностранная компания обязана встать на учёт в местных налоговых органах.",
      },
      { type: "h2", text: "Налогообложение и вычитаемые расходы" },
      {
        type: "ul",
        items: [
          "Доход вашего ПУ в Узбекистане облагается местным налогом на прибыль",
          "Налоговая база — обычно совокупный доход ПУ с учётом определённых вычетов на расходы, связанные с деятельностью",
          "Отдельные платежи от ПУ в адрес иностранной головной компании или связанных лиц могут быть невычитаемыми",
          "Чистая прибыль ПУ после налогообложения рассматривается как дивиденды и может облагаться по ставке 10% — международные налоговые соглашения могут предусматривать пониженные ставки",
        ],
      },
      {
        type: "blockquote",
        text: "Правила ПУ в Узбекистане в целом следуют принципам ОЭСР, но имеют локальную специфику. Иностранным компаниям следует получить профессиональную оценку до начала деятельности, чтобы избежать неожиданных налоговых последствий.",
      },
      { type: "h2", text: "Практические последствия" },
      {
        type: "p",
        text: "Понимание, создаёт ли ваша деятельность ПУ в Узбекистане, — критичный этап анализа выхода на рынок. Последствия незарегистрированной деятельности ПУ включают доначисления налогов, пени и репутационные риски. До принятия решения о бизнес-структуре настоятельно рекомендуется проактивно оценить операционные следы по порогам ПУ, установленным Налоговым кодексом Узбекистана и соответствующими соглашениями об избежании двойного налогообложения.",
      },
    ],
  },
  uz: {
    subtitle: "Chet ellik investorlar uchun Oʻzbekistondagi Doimiy vakolatxona talablarini tushunish va bajarish uchun muhim maslahatlar.",
    author: "Advizen soliq amaliyoti",
    readTime: "7 daqiqalik oʻqish",
    content: [
      {
        type: "p",
        text: "Oʻzbekistonda faoliyat yuritmoqchi boʻlgan chet el kompaniyalari uchun Doimiy vakolatxona (DV) tushunchasini bilish asosiydir. Mohiyatan, DV chet el kompaniyasi Oʻzbekistonda biznes faoliyatini yuritish uchun doimiy joyga ega boʻlganda paydo boʻladi. Bu jismoniy joy yoki mamlakatda davom etayotgan muayyan turdagi faoliyat boʻlishi mumkin. Bir oydan ortiq mavjud boʻlgan ish joyi odatda doimiy hisoblanadi.",
      },
      { type: "h2", text: "DV deb hisoblanishi mumkin boʻlgan narsalar" },
      {
        type: "p",
        text: "Turli faoliyat va mavjudlik DV maqomiga olib kelishi mumkin:",
      },
      {
        type: "ul",
        items: [
          "Jismoniy joylashuv: har qanday turdagi ofis (boshqaruv, filial, byuro), zavod, ustaxona yoki laboratoriya",
          "Ishlab chiqarish va sotish: tovarlarni ishlab chiqarish, qayta ishlash yoki qadoqlash, yoki omborni sotuv nuqtasi sifatida ishlatish",
          "Resurs qazib olish: tog'-kon, neft yoki gaz quduqlari, karyerlar yoki har qanday tabiiy resurslarni qazib olish bilan bogʻliq faoliyat",
          "Uzoq muddatli loyihalar va xizmatlar: 183 kundan ortiq davom etadigan qurilish, montaj yoki oʻrnatish loyihalari; yoki kamida 183 kun davomida xodimlar orqali xizmatlar koʻrsatish",
          "Sugʻurta va agentlik: bogʻliq agent orqali sugʻurta mukofotlarini yigʻuvchi chet el sugʻurta kompaniyalari yoki chet el kompaniyasi nomidan muntazam ravishda shartnomalar tuzuvchi shaxslar",
        ],
      },
      { type: "h2", text: "DV qachon paydo boʻlmaydi?" },
      {
        type: "p",
        text: "Muayyan faoliyat odatda tayyorgarlik yoki yordamchi xarakterga ega va avtomatik ravishda DV ga olib kelmaydi:",
      },
      {
        type: "ul",
        items: [
          "Saqlash va namoyish: obyektlarni faqat tovarlarni saqlash yoki namoyish qilish uchun ishlatish",
          "Cheklangan faoliyat: faqat tovar sotib olish yoki tayyorgarlik maqsadida maʼlumot toʻplash uchun doimiy biznes joyini saqlash",
          "Xodimlar taqdim etish (shartlar bilan): Oʻzbekistondagi boshqa kompaniyaga chet el xodimlarini taqdim etish odatda DV yaratmaydi, agar kompaniyangiz ularning ish natijalari uchun javobgar boʻlmasa va bundan oladigan daromad bunday xodimlarni taqdim etish jami xarajatlarining 10% dan oshmasa",
        ],
      },
      { type: "h2", text: "Faoliyatni boshlash va roʻyxatga olish" },
      {
        type: "p",
        text: "Agar faoliyatingiz DV ga ishora qilsa, odatda Oʻzbekistonda bir nechta asosiy sanalardan eng erta sanasida — masalan, tegishli shartnomalarni imzolash yoki shartnomani bajarish uchun xodimlar kelishi sanasida — faoliyat boshlangan deb hisoblanadi. DV paydo boʻlganda, chet el kompaniyangiz mahalliy soliq organlarida roʻyxatdan oʻtishi shart.",
      },
      { type: "h2", text: "Soliq solish va chegirib tashlanadigan xarajatlar" },
      {
        type: "ul",
        items: [
          "Sizning DV ingiz tomonidan Oʻzbekistonda yaratilgan daromad mahalliy foyda soligʻiga tortiladi",
          "Soliq bazasi odatda DV ning umumiy daromadi boʻlib, biznes bilan bogʻliq xarajatlar uchun muayyan chegirmalar hisobga olinadi",
          "DV dan chet el bosh ofisi yoki boshqa bogʻliq shaxslarga ayrim toʻlovlar chegirib tashlanmasligi mumkin",
          "Soliqdan keyingi DV ning sof foydasi dividend sifatida koʻrib chiqiladi va 10% soliqqa tortilishi mumkin — xalqaro soliq shartnomalari pastroq stavkalarni taklif qilishi mumkin",
        ],
      },
      {
        type: "blockquote",
        text: "Oʻzbekistonda DV qoidalari OECD tamoyillariga juda yaqin, biroq mahalliy oʻziga xosliklarga ega. Chet el kompaniyalari kutilmagan soliq taʼsiridan qochish uchun faoliyatni boshlashdan oldin professional baholash olishi kerak.",
      },
      { type: "h2", text: "Amaliy oqibatlar" },
      {
        type: "p",
        text: "Faoliyatingiz Oʻzbekistonda DV yaratadimi degan savolni tushunish har qanday bozorga kirish tahlilida muhim qadamdir. Roʻyxatga olinmagan DV faoliyatining oqibatlari orasida soliq qoʻshib hisoblash, jarimalar va obroʻga zarar bor. Biznes tuzilmasini tanlashdan oldin faoliyatingizni Oʻzbekiston Soliq kodeksi va tegishli qoʻsh soliqqa tortishni bartaraf etish toʻgʻrisidagi shartnomalar belgilagan DV chegaralariga proaktiv baholash tavsiya etiladi.",
      },
    ],
  },
};

export default article;
